import Foundation

struct HistoricalFactsData {

    static let facts: [HistoricalFact] = [

        // 🧘‍♂️ RELIGION & CULTURE (35)
        HistoricalFact(text: "The sacred Sri Maha Bodhi Tree in Anuradhapura is the oldest historically authenticated tree in the world.", category: .religion),
        HistoricalFact(text: "Princess Sanghamitta brought a sapling of the Bodhi tree from India to Sri Lanka.", category: .religion),
        HistoricalFact(text: "The Mahavihara in Anuradhapura was the center of Theravada Buddhism.", category: .religion),
        HistoricalFact(text: "The Abhayagiri Monastery became a major international Buddhist university.", category: .religion),
        HistoricalFact(text: "The Jethawanaramaya stupa is one of the tallest ancient structures ever built.", category: .religion),
        HistoricalFact(text: "Ancient monks studied meditation, astronomy, medicine, and logic.", category: .religion),
        HistoricalFact(text: "Thuparamaya is the first stupa built after the arrival of Buddhism.", category: .religion),
        HistoricalFact(text: "Stupa relic chambers contained gems, gold, and sacred artifacts.", category: .religion),
        HistoricalFact(text: "Monastic complexes included libraries, refectories, and bathing ponds.", category: .religion),
        HistoricalFact(text: "Monks guided kings on moral governance and social welfare.", category: .religion),
        HistoricalFact(text: "Anuradhapura hosted large Buddhist festivals bringing communities together.", category: .religion),
        HistoricalFact(text: "Bodhi tree shrines were central worship places for the public.", category: .religion),
        HistoricalFact(text: "Temple murals depicted Jataka stories with moral lessons.", category: .religion),
        HistoricalFact(text: "The Abhayagiri monks created advanced commentaries on Buddhist doctrine.", category: .religion),
        HistoricalFact(text: "Offering flowers symbolized impermanence and devotion.", category: .religion),
        HistoricalFact(text: "Sri Lankan monks wrote manuscripts on medicine and Ayurveda.", category: .religion),
        HistoricalFact(text: "The massive Ruwanwelisaya symbolizes purity and spiritual protection.", category: .religion),
        HistoricalFact(text: "Pilgrims from Southeast Asia visited Anuradhapura frequently.", category: .religion),
        HistoricalFact(text: "Some monasteries maintained herbal medicinal gardens.", category: .religion),
        HistoricalFact(text: "Temple bells signaled rituals, meditation, and dawn ceremonies.", category: .religion),
        HistoricalFact(text: "Moonstones symbolize the Buddhist path toward enlightenment.", category: .religion),
        HistoricalFact(text: "Guard stones protected temple entrances spiritually.", category: .religion),
        HistoricalFact(text: "Large alms halls fed thousands of monks daily.", category: .religion),
        HistoricalFact(text: "The Sangha maintained high ethical and environmental discipline.", category: .religion),
        HistoricalFact(text: "The Bodhi Tree in Anuradhapura has been worshipped for over 2,200 years.", category: .religion),
        HistoricalFact(text: "Mihintale is believed to be the birthplace of Buddhism in Sri Lanka.", category: .religion),
        HistoricalFact(text: "Monastic caves were carved into rocky hillsides for meditation.", category: .religion),
        HistoricalFact(text: "Relics were carried in grand processions throughout the kingdom.", category: .religion),
        HistoricalFact(text: "Stone carvings reflected spiritual symbolism and artistic precision.", category: .religion),
        HistoricalFact(text: "The Tooth Relic later became a central symbol of kingship.", category: .religion),
        HistoricalFact(text: "Offerings to monks were considered a great merit.", category: .religion),
        HistoricalFact(text: "Ancient monasteries had dedicated refectories with stone troughs.", category: .religion),
        HistoricalFact(text: "The Buddhist flag colors were inspired by ancient Sri Lankan imagery.", category: .religion),
        HistoricalFact(text: "Anuradhapura was a global center of Theravada scholarship.", category: .religion),
        HistoricalFact(text: "Monastic life promoted compassion, morality, and meditation.", category: .religion),

        // 👑 KINGSHIP & GOVERNANCE (33)
        HistoricalFact(text: "King Devanampiya Tissa made Buddhism the state religion.", category: .kingship),
        HistoricalFact(text: "King Walagamba built the Abhayagiri Vihara.", category: .kingship),
        HistoricalFact(text: "Walagamba spent 14 years in exile before reclaiming his throne.", category: .kingship),
        HistoricalFact(text: "The king’s power was legitimized through the sacred Tooth Relic.", category: .kingship),
        HistoricalFact(text: "The Mahavamsa chronicles Sri Lanka’s royal lineage.", category: .kingship),
        HistoricalFact(text: "Ministers (amathi) handled agriculture, justice, and security.", category: .kingship),
        HistoricalFact(text: "Village leaders collected taxes and organized irrigation.", category: .kingship),
        HistoricalFact(text: "The treasury funded irrigation works and military units.", category: .kingship),
        HistoricalFact(text: "Kings were seen as protectors of the people and religion.", category: .kingship),
        HistoricalFact(text: "Royal decrees were carved in stone for public display.", category: .kingship),
        HistoricalFact(text: "The legal system balanced Buddhist ethics and practicality.", category: .kingship),
        HistoricalFact(text: "Sri Lanka maintained diplomatic ties with India and China.", category: .kingship),
        HistoricalFact(text: "Royal gardens served for ceremony, leisure, and agriculture.", category: .kingship),
        HistoricalFact(text: "Some kings focused on religion, others on warfare.", category: .kingship),
        HistoricalFact(text: "Elephant troops were elite units in the Sri Lankan army.", category: .kingship),
        HistoricalFact(text: "Royal scribes recorded taxes, harvests, and census information.", category: .kingship),
        HistoricalFact(text: "Prosperous kings ensured peace and abundant harvests.", category: .kingship),
        HistoricalFact(text: "Rebellions often arose from heavy taxes or weak rule.", category: .kingship),
        HistoricalFact(text: "Coronation rituals occurred near the sacred Bodhi Tree.", category: .kingship),
        HistoricalFact(text: "Royal courts included judges guided by monks and scriptures.", category: .kingship),
        HistoricalFact(text: "Armies protected irrigation channels and border provinces.", category: .kingship),
        HistoricalFact(text: "Kings sponsored colossal irrigation tanks.", category: .kingship),
        HistoricalFact(text: "Public assemblies gave villagers a voice in governance.", category: .kingship),
        HistoricalFact(text: "Some rulers created granaries for famine relief.", category: .kingship),
        HistoricalFact(text: "Royal elephants were used for war and construction.", category: .kingship),
        HistoricalFact(text: "Military units included archers, spearmen, and chariot troops.", category: .kingship),
        HistoricalFact(text: "Astrologers advised kings on auspicious dates.", category: .kingship),
        HistoricalFact(text: "Succession disputes sometimes split the kingdom.", category: .kingship),
        HistoricalFact(text: "Administrative regions were governed by provincial officers.", category: .kingship),
        HistoricalFact(text: "Kings rewarded loyal officials with land rights.", category: .kingship),
        HistoricalFact(text: "Justice emphasized rehabilitation and moral correction.", category: .kingship),
        HistoricalFact(text: "Major infractions were judged in royal tribunals.", category: .kingship),
        HistoricalFact(text: "Kingship blended spiritual duty with military leadership.", category: .kingship),

        // 🛠 ENGINEERING & IRRIGATION (32)
        HistoricalFact(text: "Sri Lanka built one of the most advanced irrigation systems in the ancient world.", category: .engineering),
        HistoricalFact(text: "The Minneriya Tank irrigates thousands of acres.", category: .engineering),
        HistoricalFact(text: "Kala Wewa reservoir stretches more than 20 kilometers.", category: .engineering),
        HistoricalFact(text: "The ‘bisokotuwa’ sluice was a unique Sri Lankan hydraulic innovation.", category: .engineering),
        HistoricalFact(text: "Engineers built spillways to protect tanks from flooding.", category: .engineering),
        HistoricalFact(text: "Jayaganga canal ran 54 miles with only 6 inches of slope.", category: .engineering),
        HistoricalFact(text: "Reservoirs were interconnected across entire regions.", category: .engineering),
        HistoricalFact(text: "Stone-lined canals prevented erosion and contamination.", category: .engineering),
        HistoricalFact(text: "Underground drains carried stormwater away from the city.", category: .engineering),
        HistoricalFact(text: "Tank bunds used layered clay, gravel, and stone.", category: .engineering),
        HistoricalFact(text: "Small village tanks fed larger regional reservoirs in a cascade system.", category: .engineering),
        HistoricalFact(text: "Bathing ponds like Kuttam Pokuna show precision engineering.", category: .engineering),
        HistoricalFact(text: "Stupas were built using geometric ratios with cosmic symbolism.", category: .engineering),
        HistoricalFact(text: "Bricks were fired with exact specifications for durability.", category: .engineering),
        HistoricalFact(text: "Some stupas were coated in copper and gold leaf.", category: .engineering),
        HistoricalFact(text: "Canals transported water long distances with minimal gradient loss.", category: .engineering),
        HistoricalFact(text: "Engineers used natural rock formations to reinforce tank structures.", category: .engineering),
        HistoricalFact(text: "Ancient planners positioned stupas according to cosmic alignment.", category: .engineering),
        HistoricalFact(text: "Lime plaster waterproofed ancient buildings and tanks.", category: .engineering),
        HistoricalFact(text: "Builders used inclined ramps to move heavy blocks.", category: .engineering),
        HistoricalFact(text: "Some tanks included islands designed to preserve wildlife.", category: .engineering),
        HistoricalFact(text: "Irrigation systems allowed rice cultivation year-round.", category: .engineering),
        HistoricalFact(text: "Hydraulic engineers were highly respected professionals.", category: .engineering),
        HistoricalFact(text: "Temple ponds were used for ritual bathing and purification.", category: .engineering),
        HistoricalFact(text: "Stone bridges connected major trade routes near Anuradhapura.", category: .engineering),
        HistoricalFact(text: "Brick stupas were once covered in bright white lime plaster.", category: .engineering),
        HistoricalFact(text: "Massive tanks resembled artificial lakes spanning miles.", category: .engineering),
        HistoricalFact(text: "Some monasteries had water-driven mechanisms for timekeeping.", category: .engineering),
        HistoricalFact(text: "The tank cascade system is now studied globally for sustainability.", category: .engineering),
        HistoricalFact(text: "Engineers developed advanced flood-control techniques.", category: .engineering),
        HistoricalFact(text: "Reservoir silt traps helped maintain water quality.", category: .engineering),
        HistoricalFact(text: "Anuradhapura’s city plan integrated water, religion, and administration seamlessly.", category: .engineering),
    ]
}
